import test from 'node:test';
import assert from 'node:assert/strict';

import {
  AUTOMATIC_LYRICS_PHASES,
  AutomaticLyricsPreparationError,
  automaticLyricsCandidateSource,
  createAutomaticLyricsDraft,
  preparedCandidateToVtt,
  validatePreparedLyricsCandidate,
} from '../src/lib/lyrics/lyricsAutoPreparation.js';

const candidate = {
  schemaVersion: 1,
  videoId: 'abcdefghijk',
  status: 'review_required',
  language: 'ja',
  sourceKind: 'youtube_auto_caption',
  sourceTitle: 'Synthetic timed captions',
  sourceUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
  retrievedAt: 123,
  autoGenerated: false,
  cues: [
    { anchorMs: 1_000, text: 'first line' },
    { anchorMs: 4_500, text: 'second line' },
  ],
};

test('prepared lyrics candidates remain bounded, ordered, and tied to one video', () => {
  const normalized = validatePreparedLyricsCandidate(candidate, 'abcdefghijk');
  assert.equal(normalized.cues.length, 2);
  assert.equal(validatePreparedLyricsCandidate(candidate, 'different01'), null);
  assert.equal(validatePreparedLyricsCandidate({
    ...candidate,
    sourceKind: 'youtube_manual_caption',
  }, candidate.videoId).originalTextPolicy, 'verbatim');
  assert.equal(validatePreparedLyricsCandidate({
    ...candidate,
    sourceKind: 'youtube_discovered_manual_caption',
    timingEstimated: true,
  }, candidate.videoId).originalTextPolicy, 'verbatim');
  assert.equal(validatePreparedLyricsCandidate({
    ...candidate,
    cues: [...candidate.cues].reverse(),
  }, candidate.videoId), null);
  assert.match(preparedCandidateToVtt(normalized), /00:00:01\.000 --> 00:00:04\.499/);
});

test('automatic preparation translates the whole timed source and stops at review required', async () => {
  const phases = [];
  const draft = await createAutomaticLyricsDraft({
    song: { src: candidate.videoId, title: 'Synthetic', artist: 'Fixture' },
    candidate,
    translate: async (input) => ({
      correctedOriginalLines: input.originalLines.map((line, index) => index === 0 ? 'first line!' : line),
      translations: input.originalLines.map((line) => `ko:${line}`),
      sourceTier: 'machine_contextual',
      providerId: 'fixture-translator',
    }),
    onPhase: (phase) => phases.push(phase),
  });

  assert.deepEqual(phases, [
    AUTOMATIC_LYRICS_PHASES.COLLECTING,
    AUTOMATIC_LYRICS_PHASES.TRANSLATING,
    AUTOMATIC_LYRICS_PHASES.REVIEW_REQUIRED,
  ]);
  assert.equal(draft.reviewRequired, true);
  assert.equal(draft.mappingDrafts.length, 2);
  assert.equal(draft.translationSourceTier, 'machine_contextual');
  assert.match(draft.originalText, /^WEBVTT/);
  assert.match(draft.originalText, /first line!/);
  assert.equal(draft.correctionCount, 1);
  assert.equal(draft.timingEstimated, false);
});

test('automatic preparation contextually corrects Korean captions without skipping the provider', async () => {
  let request = null;
  const draft = await createAutomaticLyricsDraft({
    song: { src: candidate.videoId, title: '한국어 곡' },
    candidate: {
      ...candidate,
      language: 'ko',
      cues: [{ anchorMs: 1_000, text: '맞춤뻡 오류' }],
    },
    translate: async (input) => {
      request = input;
      return {
        correctedOriginalLines: ['맞춤법 오류'],
        translations: ['맞춤법 오류'],
        sourceTier: 'machine_contextual',
        providerId: 'fixture-polisher',
      };
    },
  });

  assert.equal(request.originalLanguage, 'ko');
  assert.match(draft.originalText, /맞춤법 오류/);
  assert.equal(draft.translationText, '맞춤법 오류');
  assert.equal(draft.correctionCount, 1);
  assert.equal(draft.translationProviderId, 'fixture-polisher');
});

test('grounded plain lyrics enter review with explicit estimated timing', async () => {
  let translationRequest = null;
  const draft = await createAutomaticLyricsDraft({
    song: { src: candidate.videoId },
    candidate: {
      ...candidate,
      sourceKind: 'gemini_grounded_web_lyrics',
      cues: undefined,
      lines: ['alpha', 'beta'],
      timingEstimated: true,
      discoveryPath: ['lrclib', 'google_search', 'namuwiki'],
    },
    translate: async (request) => {
      translationRequest = request;
      return {
        correctedOriginalLines: request.originalLines,
        translations: ['알파', '베타'],
        sourceTier: 'machine_contextual',
        providerId: 'fixture-translator',
      };
    },
  });

  assert.equal(translationRequest.preserveOriginal, true);
  assert.equal(draft.originalFileName, `automatic-${candidate.videoId}.txt`);
  assert.equal(draft.originalText, 'alpha\nbeta');
  assert.equal(draft.originalTextLocked, true);
  assert.equal(draft.timingEstimated, true);
  assert.deepEqual(draft.discoveryPath, ['lrclib', 'google_search', 'namuwiki']);
});

test('verified web lyrics fail closed when the model rewrites the source text', async () => {
  await assert.rejects(createAutomaticLyricsDraft({
    song: { src: candidate.videoId },
    candidate: {
      ...candidate,
      sourceKind: 'gemini_grounded_web_lyrics',
      cues: undefined,
      lines: ['source lyric'],
    },
    translate: async () => ({
      correctedOriginalLines: ['unrelated generated sentence'],
      translations: ['무관한 생성 문장'],
    }),
  }), (error) => error instanceof AutomaticLyricsPreparationError
    && error.code === 'lyrics_original_rewrite_blocked');
});

test('caption correction rejects unrelated replacement text', async () => {
  await assert.rejects(createAutomaticLyricsDraft({
    song: { src: candidate.videoId },
    candidate,
    translate: async () => ({
      correctedOriginalLines: ['completely unrelated prose', 'second line'],
      translations: ['무관한 문장', '둘째 줄'],
    }),
  }), (error) => error instanceof AutomaticLyricsPreparationError
    && error.code === 'lyrics_correction_untrusted');
});

test('automatic preparation never fabricates a translation when the provider fails', async () => {
  await assert.rejects(
    createAutomaticLyricsDraft({
      song: { src: candidate.videoId },
      candidate,
      translate: async () => { throw new Error('offline'); },
    }),
    (error) => error instanceof AutomaticLyricsPreparationError
      && error.code === 'lyrics_translation_failed',
  );
});

test('automatic preparation falls back to web only when prepared captions are absent or terminal', () => {
  assert.equal(automaticLyricsCandidateSource(null), 'web');
  assert.equal(automaticLyricsCandidateSource({ status: 'unavailable' }), 'web');
  assert.equal(automaticLyricsCandidateSource({ status: 'failed' }), 'web');
  assert.equal(automaticLyricsCandidateSource({ status: 'review_required' }), 'prepare');
  assert.equal(automaticLyricsCandidateSource({ status: 'ready' }), 'prepare');
  assert.equal(automaticLyricsCandidateSource({ status: 'collecting' }), null);
});
