import test from 'node:test';
import assert from 'node:assert/strict';

import {
  GEMINI_VIDEO_MODEL,
  parseSyncedLyrics,
  searchLrclibLyrics,
  selectLrclibCandidate,
  transcribeYoutubeLyricsWithGemini,
  validateGeminiLyricsResult,
  validateLyricsSearchRequest,
} from '../functions/api/lyrics-search.js';

const input = validateLyricsSearchRequest({
  videoId: 'abcdefghijk',
  title: 'Synthetic Song',
  artist: 'Example Artist',
  durationMs: 180_000,
});

test('synced web lyrics normalize into bounded timed cues', () => {
  assert.deepEqual(parseSyncedLyrics('[00:01.20]alpha\r\n[00:02.345][00:03.00]<00:02.34>beta'), [
    { anchorMs: 1_200, text: 'alpha' },
    { anchorMs: 2_345, text: 'beta' },
    { anchorMs: 3_000, text: 'beta' },
  ]);
  assert.equal(parseSyncedLyrics('plain text only').length, 0);
});

test('web search selects a matching synchronized candidate with explicit provenance', () => {
  const candidate = selectLrclibCandidate(input, [
    { id: 1, trackName: 'Different Song', artistName: 'Other Artist', duration: 180, syncedLyrics: '[00:01.00]wrong' },
    { id: 2, trackName: 'Synthetic Song', artistName: 'Example Artist', duration: 181, lang: 'en', syncedLyrics: '[00:01.00]alpha' },
  ]);
  assert.equal(candidate.sourceKind, 'lrclib_synced_lyrics');
  assert.equal(candidate.sourceUrl, 'https://lrclib.net/api/get/2');
  assert.equal(candidate.status, 'review_required');
  assert.deepEqual(candidate.cues, [{ anchorMs: 1_000, text: 'alpha' }]);
});

test('web search calls only the fixed provider endpoint and returns the prepared candidate', async () => {
  let requestedUrl = '';
  const candidate = await searchLrclibLyrics(input, async (url) => {
    requestedUrl = String(url);
    return new Response(JSON.stringify([
      { id: 3, trackName: 'Synthetic Song', artistName: 'Example Artist', duration: 180, syncedLyrics: '[00:01.00]alpha' },
    ]), { status: 200, headers: { 'Content-Type': 'application/json' } });
  });
  const parsedUrl = new URL(requestedUrl);
  assert.equal(parsedUrl.origin + parsedUrl.pathname, 'https://lrclib.net/api/search');
  assert.equal(parsedUrl.searchParams.get('track_name'), input.title);
  assert.equal(parsedUrl.searchParams.get('artist_name'), input.artist);
  assert.equal(candidate.videoId, input.videoId);
});

test('web search request rejects missing identity or unbounded metadata', () => {
  assert.equal(validateLyricsSearchRequest({ title: 'Synthetic Song' }), null);
  assert.equal(validateLyricsSearchRequest({ videoId: 'bad', title: 'Synthetic Song' }), null);
});

test('Gemini video transcript stays a review-only generated candidate', async () => {
  let requestBody;
  const candidate = await transcribeYoutubeLyricsWithGemini(input, 'test-key', async (url, init) => {
    assert.equal(String(url), 'https://generativelanguage.googleapis.com/v1beta/interactions');
    requestBody = JSON.parse(init.body);
    return new Response(JSON.stringify({
      steps: [{ type: 'model_output', content: [{
        type: 'text',
        text: JSON.stringify({ language: 'en', cues: [{ anchorMs: 1_250, text: 'synthetic line' }] }),
      }] }],
    }), { status: 200, headers: { 'Content-Type': 'application/json' } });
  });
  assert.deepEqual(requestBody.input[1], {
    type: 'video',
    uri: 'https://www.youtube.com/watch?v=abcdefghijk',
  });
  assert.equal(requestBody.model, GEMINI_VIDEO_MODEL);
  assert.equal(requestBody.response_format, undefined);
  assert.equal(candidate.sourceKind, 'gemini_youtube_transcription');
  assert.equal(candidate.status, 'review_required');
  assert.equal(candidate.autoGenerated, true);
  assert.deepEqual(candidate.cues, [{ anchorMs: 1_250, text: 'synthetic line' }]);
});

test('Gemini video transcript rejects empty and out-of-range generated cues', () => {
  assert.equal(validateGeminiLyricsResult({ language: 'en', cues: [] }, input), null);
  assert.equal(validateGeminiLyricsResult({
    language: 'en',
    cues: [{ anchorMs: input.durationMs + 30_001, text: 'late invention' }],
  }, input), null);
});
