import test from 'node:test';
import assert from 'node:assert/strict';

import {
  AUTOMATIC_LYRICS_PHASES,
  AutomaticLyricsPreparationError,
  createAutomaticLyricsDraft,
  preparedCandidateToVtt,
  validatePreparedLyricsCandidate,
} from '../src/lib/lyrics/lyricsAutoPreparation.js';

const candidate = {
  schemaVersion: 1,
  videoId: 'abcdefghijk',
  status: 'review_required',
  language: 'ja',
  sourceKind: 'youtube_manual_caption',
  sourceTitle: 'Synthetic timed captions',
  sourceUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
  retrievedAt: 123,
  autoGenerated: false,
  cues: [
    { anchorMs: 1_000, text: 'first line' },
    { anchorMs: 4_500, text: 'second line' },
  ],
};

test('prepared lyrics candidates remain bounded, ordered, and tied to one video', () => {
  const normalized = validatePreparedLyricsCandidate(candidate, 'abcdefghijk');
  assert.equal(normalized.cues.length, 2);
  assert.equal(validatePreparedLyricsCandidate(candidate, 'different01'), null);
  assert.equal(validatePreparedLyricsCandidate({
    ...candidate,
    cues: [...candidate.cues].reverse(),
  }, candidate.videoId), null);
  assert.match(preparedCandidateToVtt(normalized), /00:00:01\.000 --> 00:00:04\.499/);
});

test('automatic preparation translates the whole timed source and stops at review required', async () => {
  const phases = [];
  const draft = await createAutomaticLyricsDraft({
    song: { src: candidate.videoId, title: 'Synthetic', artist: 'Fixture' },
    candidate,
    translate: async (input) => ({
      translations: input.originalLines.map((line) => `ko:${line}`),
      sourceTier: 'machine_contextual',
      providerId: 'fixture-translator',
    }),
    onPhase: (phase) => phases.push(phase),
  });

  assert.deepEqual(phases, [
    AUTOMATIC_LYRICS_PHASES.COLLECTING,
    AUTOMATIC_LYRICS_PHASES.TRANSLATING,
    AUTOMATIC_LYRICS_PHASES.REVIEW_REQUIRED,
  ]);
  assert.equal(draft.reviewRequired, true);
  assert.equal(draft.mappingDrafts.length, 2);
  assert.equal(draft.translationSourceTier, 'machine_contextual');
  assert.match(draft.originalText, /^WEBVTT/);
});

test('automatic preparation never fabricates a translation when the provider fails', async () => {
  await assert.rejects(
    createAutomaticLyricsDraft({
      song: { src: candidate.videoId },
      candidate,
      translate: async () => { throw new Error('offline'); },
    }),
    (error) => error instanceof AutomaticLyricsPreparationError
      && error.code === 'lyrics_translation_failed',
  );
});
