import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

import {
  PrepareQueue,
  prepareWakeFrame,
} from '../workers/rekasong-session/src/index.js';

test('prepare wake frame is a stable versioned non-authoritative hint', () => {
  assert.deepEqual(JSON.parse(prepareWakeFrame('app_active', 1234)), {
    type: 'prepare.wake',
    version: 1,
    reason: 'app_active',
    sentAt: 1234,
  });
});

test('app activity and enqueue wake every connected prepare worker', async () => {
  const frames = [];
  const jobs = new Map();
  const sockets = Array.from({ length: 2 }, () => {
    let attachment = {};
    return {
      send: (frame) => frames.push(JSON.parse(frame)),
      deserializeAttachment: () => attachment,
      serializeAttachment: (value) => {
        attachment = value;
      },
    };
  });
  const queue = new PrepareQueue({
    storage: {
      put: async (key, value) => jobs.set(key, value),
    },
    getWebSockets: (tag) => {
      assert.equal(tag, 'prepare-worker');
      return sockets;
    },
  }, {});

  assert.equal(queue.lastActivityWakeAt, 0);
  const activityResponse = queue.noteAppActivity();
  assert.equal(activityResponse.status, 204);
  assert.deepEqual(frames.map((frame) => frame.reason), ['app_active', 'app_active']);
  const duplicateActivityResponse = queue.noteAppActivity();
  assert.equal(duplicateActivityResponse.status, 204);
  assert.deepEqual(
    frames.map((frame) => frame.reason),
    ['app_active', 'app_active'],
    'activity wake must be globally coalesced during the cooldown',
  );

  const rehydratedQueue = new PrepareQueue({
    storage: queue.ctx.storage,
    getWebSockets: queue.ctx.getWebSockets,
  }, {});
  rehydratedQueue.noteAppActivity();
  assert.deepEqual(
    frames.map((frame) => frame.reason),
    ['app_active', 'app_active'],
    'activity cooldown must survive Durable Object hibernation',
  );

  const job = await queue.enqueue('abcdefghijk', null);
  assert.equal(job.status, 'queued');
  assert.equal(jobs.get('job:abcdefghijk').status, 'queued');
  assert.deepEqual(frames.map((frame) => frame.reason), [
    'app_active',
    'app_active',
    'job_enqueued',
    'job_enqueued',
  ]);
});

test('prepare wake routes keep browser and worker authentication boundaries separate', async () => {
  const source = await readFile(
    new URL('../workers/rekasong-session/src/index.js', import.meta.url),
    'utf8',
  );

  assert.match(
    source,
    /url\.pathname === '\/v1\/prepare\/activity' && request\.method === 'POST'/,
  );
  assert.match(
    source,
    /url\.pathname === '\/v1\/prepare\/wake' && request\.method === 'GET'/,
  );
  assert.match(source, /await this\.verifyWorker\(request\)/);
  assert.match(source, /this\.ctx\.acceptWebSocket\(server, \[PREPARE_WAKE_WORKER_TAG\]\)/);
  assert.match(source, /socket\.deserializeAttachment\?\.\(\)/);
  assert.match(source, /lastActivityWakeAt/);
  assert.match(source, /this\.signalWorkers\('job_enqueued'\)/);
  assert.match(source, /streamPreparedLyrics/);
  assert.match(source, /verifyRoomPlayerToken\(request, env\)/);
  assert.match(source, /action === 'lyrics' && request\.method === 'PUT'/);
});

test('prepare jobs persist a bounded lyrics outcome before audio readiness', async () => {
  const jobs = new Map([['job:abcdefghijk', {
    videoId: 'abcdefghijk',
    status: 'preparing',
    createdAt: 1,
    attempts: 1,
  }]]);
  const stored = new Map();
  const queue = new PrepareQueue({
    storage: {
      get: async (key) => jobs.get(key),
      put: async (key, value) => jobs.set(key, value),
    },
    getWebSockets: () => [],
  }, {
    PREPARE_TOKEN: 'secret',
    MEDIA_BUCKET: {
      put: async (key, value) => stored.set(key, value),
      delete: async (key) => stored.delete(key),
    },
  });
  const candidate = {
    schemaVersion: 1,
    videoId: 'abcdefghijk',
    status: 'review_required',
    language: 'ja',
    sourceKind: 'youtube_manual_caption',
    sourceTitle: 'Synthetic caption',
    sourceUrl: 'https://www.youtube.com/watch?v=abcdefghijk',
    retrievedAt: 123,
    autoGenerated: false,
    cues: [{ anchorMs: 1000, text: 'synthetic line' }],
  };
  const body = JSON.stringify(candidate);
  const response = await queue.uploadPreparedLyrics(new Request(
    'https://worker.test/v1/prepare/abcdefghijk/lyrics',
    {
      method: 'PUT',
      headers: {
        Authorization: 'Bearer secret',
        'Content-Type': 'application/json',
        'Content-Length': String(new TextEncoder().encode(body).byteLength),
      },
      body,
    },
  ), 'abcdefghijk');

  assert.equal(response.status, 200);
  assert.deepEqual(jobs.get('job:abcdefghijk').lyrics, {
    status: 'review_required',
    language: 'ja',
    sourceKind: 'youtube_manual_caption',
    cueCount: 1,
    reason: '',
  });
  assert.ok(stored.has('lyrics-candidates/youtube/abcdefghijk.json'));
});

test('force retry requeues a ready audio job whose lyrics alone failed', async () => {
  const jobs = new Map([['job:abcdefghijk', {
    videoId: 'abcdefghijk',
    status: 'ready',
    createdAt: 1,
    attempts: 1,
    lyrics: {
      status: 'failed',
      language: 'en',
      sourceKind: 'youtube_manual_caption',
      cueCount: 0,
      reason: 'caption_download_failed',
    },
  }]]);
  const queue = new PrepareQueue({
    storage: {
      get: async (key) => jobs.get(key),
      put: async (key, value) => jobs.set(key, value),
    },
    getWebSockets: () => [],
  }, {
    MEDIA_BUCKET: { head: async () => ({ size: 1 }) },
  });

  const response = await queue.requestPrepare(new Request('https://worker.test/v1/prepare', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ videoId: 'abcdefghijk', force: true }),
  }));

  assert.equal(response.status, 202);
  assert.deepEqual(jobs.get('job:abcdefghijk').lyrics, {
    status: 'collecting',
    language: '',
    sourceKind: '',
    cueCount: 0,
    reason: '',
  });
});

test('prepare queue sanitizes song identity and passes it only to the claimed worker job', async () => {
  const jobs = new Map();
  const storage = {
    get: async (key) => jobs.get(key),
    put: async (key, value) => jobs.set(key, value),
    list: async ({ prefix }) => new Map([...jobs].filter(([key]) => key.startsWith(prefix))),
    setAlarm: async () => {},
    deleteAlarm: async () => {},
  };
  const queue = new PrepareQueue({ storage, getWebSockets: () => [] }, { PREPARE_TOKEN: 'secret' });
  const queued = await queue.requestPrepare(new Request('https://worker.test/v1/prepare', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      videoId: 'abcdefghijk',
      lyricsSearch: {
        title: '  Moon\u0000   Song  ',
        artist: ' Artist A ',
        source: 'songbook',
      },
    }),
  }));
  assert.equal(queued.status, 202);

  const claimed = await queue.claim(new Request('https://worker.test/v1/prepare/claim', {
    method: 'POST',
    headers: { Authorization: 'Bearer secret' },
  }));
  assert.equal(claimed.status, 200);
  assert.deepEqual((await claimed.json()).lyricsSearch, {
    title: 'Moon Song',
    artist: 'Artist A',
    source: 'songbook',
  });
});
