import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { songbookLyricsCatalogKey } from '../src/lib/lyrics/lyricsSearchClient.js';

const catalogDir = path.resolve('public/lyrics-catalog/v1');

test('bundled Eureka catalog is internally complete and identity-safe', async () => {
  const manifest = JSON.parse(await readFile(path.join(catalogDir, 'manifest.json'), 'utf8'));
  const bundled = manifest.coverage.filter((entry) => entry.status === 'bundled');
  const missing = manifest.coverage.filter((entry) => entry.status === 'missing');

  assert.equal(manifest.songbook.total, 949);
  assert.equal(manifest.coverage.length, manifest.songbook.total);
  assert.equal(new Set(manifest.coverage.map((entry) => entry.key)).size, manifest.coverage.length);
  assert.equal(bundled.length, manifest.bundled);
  assert.equal(missing.length, manifest.missing);
  assert.equal(bundled.length + missing.length, manifest.songbook.total);

  for (const entry of manifest.coverage) {
    assert.equal(entry.key, await songbookLyricsCatalogKey(entry));
  }

  for (const entry of bundled) {
    const record = JSON.parse(await readFile(path.join(catalogDir, `${entry.key}.json`), 'utf8'));
    assert.equal(record.title, entry.title);
    assert.equal(record.artist, entry.artist);
    assert.equal(record.lines.length, record.translations.length);
    assert.ok(record.lines.length > 0);
    assert.ok(record.lines.every((line) => typeof line === 'string' && line.trim()));
    assert.ok(record.translations.every((line) => typeof line === 'string' && line.trim()));
    assert.equal(record.originalTextPolicy, 'verbatim');
    assert.equal(record.autoGenerated, false);
  }
});
