import { sha256TextHash } from './lyricsPackage.js';

export const AUTOMATIC_LYRICS_PHASES = Object.freeze({
  COLLECTING: 'collecting',
  TRANSLATING: 'translating',
  REVIEW_REQUIRED: 'review_required',
  READY: 'ready',
  FAILED: 'failed',
});

const MAX_CUES = 2_000;
const MAX_TEXT_LENGTH = 500;
const allowedCandidateStatuses = new Set(['ready', 'review_required']);
const verbatimSourceKinds = new Set([
  'youtube_manual_caption',
  'youtube_discovered_manual_caption',
  'lrclib_synced_lyrics',
  'gemini_grounded_web_lyrics',
  'gemini_grounded_official_web_lyrics',
]);

const bounded = (value, max = 240) => String(value ?? '').trim().slice(0, max);

export const automaticLyricsIdentity = (song) => JSON.stringify([
  bounded(song?.title, 240).normalize('NFC'),
  bounded(song?.artist, 240).normalize('NFC'),
]);

export class AutomaticLyricsPreparationError extends Error {
  constructor(code, cause = null) {
    super(code, { cause });
    this.name = 'AutomaticLyricsPreparationError';
    this.code = code;
  }
}

export function validatePreparedLyricsCandidate(value, expectedVideoId = '') {
  if (!value || typeof value !== 'object' || Array.isArray(value)
    || value.schemaVersion !== 1
    || !allowedCandidateStatuses.has(value.status)
    || (expectedVideoId && value.videoId !== expectedVideoId)
    || (value.cues != null && !Array.isArray(value.cues))
    || (value.lines != null && !Array.isArray(value.lines))) return null;

  let previousAnchor = -1;
  const cues = [];
  for (const cue of value.cues || []) {
    const anchorMs = Number(cue?.anchorMs);
    const text = String(cue?.text ?? '').normalize('NFC').trim();
    if (!Number.isFinite(anchorMs) || anchorMs < previousAnchor || anchorMs < 0
      || !text || text.length > MAX_TEXT_LENGTH) return null;
    previousAnchor = anchorMs;
    cues.push(Object.freeze({ anchorMs, text }));
  }
  const lines = cues.length > 0
    ? cues.map((cue) => cue.text)
    : (value.lines || []).map((line) => String(line ?? '').normalize('NFC').trim());
  if (lines.length === 0 || lines.length > MAX_CUES
    || lines.some((line) => !line || line.length > MAX_TEXT_LENGTH)) return null;
  const sourceKind = bounded(value.sourceKind, 80) || 'youtube_caption';

  return Object.freeze({
    schemaVersion: 1,
    videoId: bounded(value.videoId, 11),
    status: value.status,
    language: bounded(value.language, 16) || 'und',
    sourceKind,
    sourceTitle: bounded(value.sourceTitle, 240),
    sourceUrl: bounded(value.sourceUrl, 1_024) || null,
    retrievedAt: Number.isFinite(value.retrievedAt) ? value.retrievedAt : Date.now(),
    autoGenerated: value.autoGenerated === true,
    originalTextPolicy: value.originalTextPolicy === 'verbatim' || verbatimSourceKinds.has(sourceKind)
      ? 'verbatim'
      : 'caption_correction',
    timingEstimated: cues.length === 0 || value.timingEstimated === true,
    discoveryPath: Object.freeze((Array.isArray(value.discoveryPath) ? value.discoveryPath : [])
      .slice(0, 8)
      .map((item) => bounded(item, 80))
      .filter(Boolean)),
    lines: Object.freeze(lines),
    cues: Object.freeze(cues),
  });
}

const timestamp = (milliseconds) => {
  const total = Math.max(0, Math.round(milliseconds));
  const hours = Math.floor(total / 3_600_000);
  const minutes = Math.floor((total % 3_600_000) / 60_000);
  const seconds = Math.floor((total % 60_000) / 1_000);
  const millis = total % 1_000;
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
};

export function preparedCandidateToVtt(candidate) {
  const cues = candidate?.cues || [];
  const blocks = cues.map((cue, index) => {
    const nextAnchor = cues[index + 1]?.anchorMs;
    const endMs = Number.isFinite(nextAnchor)
      ? Math.max(cue.anchorMs + 250, nextAnchor - 1)
      : cue.anchorMs + 4_000;
    return `${index + 1}\n${timestamp(cue.anchorMs)} --> ${timestamp(endMs)}\n${cue.text}`;
  });
  return `WEBVTT\n\n${blocks.join('\n\n')}\n`;
}

const isKorean = (language) => /^ko(?:-|$)/iu.test(language || '');

function isPlausibleCaptionCorrection(sourceValue, correctedValue) {
  const source = String(sourceValue).normalize('NFKC').trim();
  const corrected = String(correctedValue).normalize('NFKC').trim();
  if (source === corrected) return true;
  const limit = Math.min(12, Math.max(1, Math.floor(source.length * 0.25)));
  if (Math.abs(source.length - corrected.length) > limit) return false;

  let previous = Array(corrected.length + 1).fill(limit + 1);
  for (let column = 0; column <= Math.min(corrected.length, limit); column += 1) previous[column] = column;
  for (let row = 1; row <= source.length; row += 1) {
    const current = Array(corrected.length + 1).fill(limit + 1);
    if (row <= limit) current[0] = row;
    const start = Math.max(1, row - limit);
    const end = Math.min(corrected.length, row + limit);
    for (let column = start; column <= end; column += 1) {
      current[column] = Math.min(
        previous[column] + 1,
        current[column - 1] + 1,
        previous[column - 1] + (source[row - 1] === corrected[column - 1] ? 0 : 1),
      );
    }
    previous = current;
  }
  return previous[corrected.length] <= limit;
}

export function automaticLyricsCandidateSource(lyricsInfo) {
  if (!lyricsInfo || ['failed', 'unavailable'].includes(lyricsInfo.status)) return 'web';
  return ['ready', 'review_required'].includes(lyricsInfo.status) ? 'prepare' : null;
}

export async function createAutomaticLyricsDraft({
  song,
  candidate: rawCandidate,
  translate,
  onPhase = () => {},
} = {}) {
  onPhase(AUTOMATIC_LYRICS_PHASES.COLLECTING);
  const candidate = validatePreparedLyricsCandidate(rawCandidate, song?.src || '');
  if (!candidate) throw new AutomaticLyricsPreparationError('lyrics_candidate_invalid');

  const originalLines = candidate.lines;
  const contentHash = await sha256TextHash(originalLines.join('\n'));
  const preserveOriginal = candidate.originalTextPolicy === 'verbatim';
  onPhase(AUTOMATIC_LYRICS_PHASES.TRANSLATING);
  let result;
  try {
    result = await translate({
      contentHash,
      title: song?.title || '',
      artist: song?.artist || '',
      originalLanguage: candidate.language,
      preserveOriginal,
      originalLines,
    });
  } catch (cause) {
    throw new AutomaticLyricsPreparationError('lyrics_translation_failed', cause);
  }
  if (!Array.isArray(result?.correctedOriginalLines)
    || result.correctedOriginalLines.length !== originalLines.length
    || result.correctedOriginalLines.some((line) => !String(line || '').trim())
    || !Array.isArray(result?.translations)
    || result.translations.length !== originalLines.length
    || result.translations.some((line) => !String(line || '').trim())) {
    throw new AutomaticLyricsPreparationError('lyrics_translation_invalid');
  }
  const providerCorrectedOriginalLines = result.correctedOriginalLines
    .map((line) => String(line).normalize('NFC').trim());
  if (preserveOriginal
    ? providerCorrectedOriginalLines.some((line, index) => line !== originalLines[index])
    : providerCorrectedOriginalLines.some((line, index) => !isPlausibleCaptionCorrection(originalLines[index], line))) {
    throw new AutomaticLyricsPreparationError(preserveOriginal
      ? 'lyrics_original_rewrite_blocked'
      : 'lyrics_correction_untrusted');
  }
  const correctedOriginalLines = preserveOriginal ? originalLines : providerCorrectedOriginalLines;
  const translations = result.translations.map((line) => String(line).normalize('NFC').trim());
  const correctionCount = correctedOriginalLines
    .filter((line, index) => line !== originalLines[index]).length;
  const translationSourceTier = result.sourceTier === 'machine_contextual'
    ? 'machine_contextual'
    : 'trusted_web';
  const translationProviderId = bounded(result.providerId, 80) || 'automatic-translation';
  const correctedCandidate = {
    ...candidate,
    cues: candidate.cues.map((cue, index) => ({ ...cue, text: correctedOriginalLines[index] })),
  };
  const correctedContentHash = await sha256TextHash(correctedOriginalLines.join('\n'));

  onPhase(AUTOMATIC_LYRICS_PHASES.REVIEW_REQUIRED);
  return Object.freeze({
    source: 'automatic_prepare',
    originalLanguage: candidate.language,
    originalText: candidate.cues.length > 0
      ? preparedCandidateToVtt(correctedCandidate)
      : correctedOriginalLines.join('\n'),
    originalFileName: candidate.cues.length > 0
      ? `automatic-${candidate.videoId}.vtt`
      : `automatic-${candidate.videoId}.txt`,
    originalSourceTier: correctionCount > 0 ? 'machine_contextual' : 'trusted_web',
    originalSourceTitle: candidate.sourceTitle || 'YouTube timed captions',
    originalSourceUrl: candidate.sourceUrl,
    originalProviderId: correctionCount > 0
      ? bounded(`${candidate.sourceKind}+contextual-polish`, 80)
      : candidate.sourceKind,
    translationText: translations.join('\n'),
    translationSourceTier,
    translationSourceTitle: isKorean(candidate.language)
      ? 'Contextual Korean caption polish'
      : 'Contextual Korean machine draft',
    translationProviderId,
    mappingDrafts: translations.map((displayKo, index) => ({
      mappingId: `M${String(index + 1).padStart(3, '0')}`,
      originalInput: String(index + 1),
      displayKo,
    })),
    reviewRequired: true,
    originalTextLocked: preserveOriginal,
    autoGenerated: candidate.autoGenerated || !isKorean(candidate.language) || correctionCount > 0,
    contentHash: correctedContentHash,
    sourceContentHash: contentHash,
    correctionCount,
    timingEstimated: candidate.timingEstimated,
    discoveryPath: candidate.discoveryPath,
  });
}
