import { sha256TextHash } from './lyricsPackage.js';

export const AUTOMATIC_LYRICS_PHASES = Object.freeze({
  COLLECTING: 'collecting',
  TRANSLATING: 'translating',
  REVIEW_REQUIRED: 'review_required',
  READY: 'ready',
  FAILED: 'failed',
});

const MAX_CUES = 2_000;
const MAX_TEXT_LENGTH = 500;
const allowedCandidateStatuses = new Set(['ready', 'review_required']);

const bounded = (value, max = 240) => String(value ?? '').trim().slice(0, max);

export class AutomaticLyricsPreparationError extends Error {
  constructor(code, cause = null) {
    super(code, { cause });
    this.name = 'AutomaticLyricsPreparationError';
    this.code = code;
  }
}

export function validatePreparedLyricsCandidate(value, expectedVideoId = '') {
  if (!value || typeof value !== 'object' || Array.isArray(value)
    || value.schemaVersion !== 1
    || !allowedCandidateStatuses.has(value.status)
    || (expectedVideoId && value.videoId !== expectedVideoId)
    || !Array.isArray(value.cues)
    || value.cues.length === 0
    || value.cues.length > MAX_CUES) return null;

  let previousAnchor = -1;
  const cues = [];
  for (const cue of value.cues) {
    const anchorMs = Number(cue?.anchorMs);
    const text = String(cue?.text ?? '').normalize('NFC').trim();
    if (!Number.isFinite(anchorMs) || anchorMs < previousAnchor || anchorMs < 0
      || !text || text.length > MAX_TEXT_LENGTH) return null;
    previousAnchor = anchorMs;
    cues.push(Object.freeze({ anchorMs, text }));
  }

  return Object.freeze({
    schemaVersion: 1,
    videoId: bounded(value.videoId, 11),
    status: value.status,
    language: bounded(value.language, 16) || 'und',
    sourceKind: bounded(value.sourceKind, 80) || 'youtube_caption',
    sourceTitle: bounded(value.sourceTitle, 240),
    sourceUrl: bounded(value.sourceUrl, 1_024) || null,
    retrievedAt: Number.isFinite(value.retrievedAt) ? value.retrievedAt : Date.now(),
    autoGenerated: value.autoGenerated === true,
    cues: Object.freeze(cues),
  });
}

const timestamp = (milliseconds) => {
  const total = Math.max(0, Math.round(milliseconds));
  const hours = Math.floor(total / 3_600_000);
  const minutes = Math.floor((total % 3_600_000) / 60_000);
  const seconds = Math.floor((total % 60_000) / 1_000);
  const millis = total % 1_000;
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}.${String(millis).padStart(3, '0')}`;
};

export function preparedCandidateToVtt(candidate) {
  const cues = candidate?.cues || [];
  const blocks = cues.map((cue, index) => {
    const nextAnchor = cues[index + 1]?.anchorMs;
    const endMs = Number.isFinite(nextAnchor)
      ? Math.max(cue.anchorMs + 250, nextAnchor - 1)
      : cue.anchorMs + 4_000;
    return `${index + 1}\n${timestamp(cue.anchorMs)} --> ${timestamp(endMs)}\n${cue.text}`;
  });
  return `WEBVTT\n\n${blocks.join('\n\n')}\n`;
}

const isKorean = (language) => /^ko(?:-|$)/iu.test(language || '');

export function automaticLyricsCandidateSource(lyricsInfo) {
  if (!lyricsInfo || ['failed', 'unavailable'].includes(lyricsInfo.status)) return 'web';
  return ['ready', 'review_required'].includes(lyricsInfo.status) ? 'prepare' : null;
}

export async function createAutomaticLyricsDraft({
  song,
  candidate: rawCandidate,
  translate,
  onPhase = () => {},
} = {}) {
  onPhase(AUTOMATIC_LYRICS_PHASES.COLLECTING);
  const candidate = validatePreparedLyricsCandidate(rawCandidate, song?.src || '');
  if (!candidate) throw new AutomaticLyricsPreparationError('lyrics_candidate_invalid');

  const originalLines = candidate.cues.map((cue) => cue.text);
  const contentHash = await sha256TextHash(originalLines.join('\n'));
  let translations = originalLines;
  let translationSourceTier = 'trusted_web';
  let translationProviderId = candidate.sourceKind;

  if (!isKorean(candidate.language)) {
    onPhase(AUTOMATIC_LYRICS_PHASES.TRANSLATING);
    let result;
    try {
      result = await translate({
        contentHash,
        title: song?.title || '',
        artist: song?.artist || '',
        originalLines,
      });
    } catch (cause) {
      throw new AutomaticLyricsPreparationError('lyrics_translation_failed', cause);
    }
    if (!Array.isArray(result?.translations)
      || result.translations.length !== originalLines.length
      || result.translations.some((line) => !String(line || '').trim())) {
      throw new AutomaticLyricsPreparationError('lyrics_translation_invalid');
    }
    translations = result.translations.map((line) => String(line).normalize('NFC').trim());
    translationSourceTier = result.sourceTier === 'machine_contextual'
      ? 'machine_contextual'
      : 'trusted_web';
    translationProviderId = bounded(result.providerId, 80) || 'automatic-translation';
  }

  onPhase(AUTOMATIC_LYRICS_PHASES.REVIEW_REQUIRED);
  return Object.freeze({
    source: 'automatic_prepare',
    originalLanguage: candidate.language,
    originalText: preparedCandidateToVtt(candidate),
    originalFileName: `youtube-${candidate.videoId}.vtt`,
    originalSourceTier: 'trusted_web',
    originalSourceTitle: candidate.sourceTitle || 'YouTube timed captions',
    originalSourceUrl: candidate.sourceUrl,
    originalProviderId: candidate.sourceKind,
    translationText: translations.join('\n'),
    translationSourceTier,
    translationSourceTitle: isKorean(candidate.language)
      ? 'Korean source captions'
      : 'Contextual Korean machine draft',
    translationProviderId,
    mappingDrafts: translations.map((displayKo, index) => ({
      mappingId: `M${String(index + 1).padStart(3, '0')}`,
      originalInput: String(index + 1),
      displayKo,
    })),
    reviewRequired: true,
    autoGenerated: candidate.autoGenerated || !isKorean(candidate.language),
    contentHash,
  });
}
